# USING DECISION TREE ALGORITHM ON SOCIAL NETWORK ADS DATASET TO FIND WHETHER A NEW CUSTOMER WILL BUY THE PRODUCT OR NOT.

In [1]:
import numpy as np
import pandas as pd


In [3]:
data=pd.read_csv("/content/Social_Network_Ads.csv")

data.head(10)

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0
5  15728773    Male   27            58000          0
6  15598044  Female   27            84000          0
7  15694829  Female   32           150000          1
8  15600575    Male   25            33000          0
9  15727311  Female   35            65000          0

In [6]:
df=data.drop(['User ID'],axis=1) 

df.head(10)

Gender  Age  EstimatedSalary  Purchased
0    Male   19            19000          0
1    Male   35            20000          0
2  Female   26            43000          0
3  Female   27            57000          0
4    Male   19            76000          0
5    Male   27            58000          0
6  Female   27            84000          0
7  Female   32           150000          1
8    Male   25            33000          0
9  Female   35            65000          0

In [7]:
df['Gender']=df['Gender'].apply({'Male':1,'Female':0}.get)

df.head()

Gender  Age  EstimatedSalary  Purchased
0       1   19            19000          0
1       1   35            20000          0
2       0   26            43000          0
3       0   27            57000          0
4       1   19            76000          0

In [10]:
x=df.drop(['Purchased'],axis=1)    # INDEPENDENT COLUMN

x.head()

Gender  Age  EstimatedSalary
0       1   19            19000
1       1   35            20000
2       0   26            43000
3       0   27            57000
4       1   19            76000

In [12]:
y=df['Purchased'].values  # DEPENDENT COLUMN

y


array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1,

In [13]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y, test_size=0.25)




In [14]:
from sklearn.tree import DecisionTreeClassifier  # USING DECISION TREE ALGORITHM

model=DecisionTreeClassifier()

model.fit(x_train,y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [15]:
prediction=model.predict(x_test)

prediction

array([1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0])

In [16]:
from sklearn.metrics import accuracy_score, confusion_matrix

cf=confusion_matrix(y_test,prediction)

ac=accuracy_score(y_test,prediction)

print(cf)

[[47  5]
 [14 34]]


In [17]:
print("The accuracy of the model is ", ac*100, "%")

The accuracy of the model is  81.0 %


In [18]:
df.head()

Gender  Age  EstimatedSalary  Purchased
0       1   19            19000          0
1       1   35            20000          0
2       0   26            43000          0
3       0   27            57000          0
4       1   19            76000          0

# NEW CUSTOMER DATA

In [28]:
data_new={'Gender':1,'Age':28,'Salary':100000}

index=[1]

In [29]:
new_customer=pd.DataFrame(data_new,index)

new_customer

Gender  Age  Salary
1       1   28  100000

In [30]:
prediction_new=model.predict(new_customer)

prediction_new

array([1])

# OUTPUT [0] MEANS THE CUSTOMER WILL NOT BUY THE PRODUCT AND OUTPUT [1] MEANS THAT THE CUSTOMER WILL BUY THE PRODUCT.

# HENCE PREDICTION MADE BY THE MODEL FOR A NEW CUSTOMER WHO IS A MALE, AGE IS 28 YEARS AND SALARY OF 100000 IS [1]. 

# SO THE NEW CUSTOMER WILL BUY THE PRODUCT.